# Generated by Django 5.2.3 on 2025-06-27 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.IntegerField()),
                ('qualifications', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('availability', models.JSONField(default=dict)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
